modoboa_webmail/urls.py
# coding: utf-8
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'modoboa_webmail.views',

    url(r'^$', "index", name="index"),
    url(r'^submailboxes', "submailboxes", name="submailboxes_get"),
    url(r'^getmailcontent', 'getmailcontent', name="mailcontent_get"),
    url(r'^unseenmsgs', 'check_unseen_messages', name="unseen_messages_check"),

    url(r'^delete/$', 'delete', name="mail_delete"),
    url(r'^move/$', "move", name="mail_move"),
    url(r'^mark/(?P<name>.+)/$', "mark", name="mail_mark"),

    url(r'^newfolder/$', "newfolder", name="folder_add"),
    url(r'^editfolder/$', "editfolder", name="folder_change"),
    url(r'^delfolder/$', "delfolder", name="folder_delete"),
    url(r'^compressfolder/$', "folder_compress", name="folder_compress"),
    url(r'^emptytrash/$', "empty", name="trash_empty"),

    url(r'^attachments/$', 'attachments', name="attachment_list"),
    url(r'^delattachment/$', 'delattachment', name="attachment_delete"),
    url(r'^getattachment/$', 'getattachment', name="attachment_get"),
)

modoboa_webmail/forms.py
# coding: utf-8

"""Webmail forms."""

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import lxml.html

from django import forms
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from modoboa.lib import parameters
from modoboa.lib.email_utils import set_email_headers

from .lib import (
    ImapEmail, create_mail_attachment
)
from .validators import validate_email_list


def html2plaintext(content):
    """HTML to plain text translation.

    :param content: some HTML content
    """
    if not content:
        return ""
    html = lxml.html.fromstring(content)
    plaintext = ""
    for ch in html.iter():
        p = None
        if ch.text is not None:
            p = ch.text.strip('\r\t\n')
        if ch.tag == "img":
            p = ch.get("alt")
        if p is None:
            continue
        plaintext += p + "\n"
    return plaintext


def make_body_images_inline(body):
    """Looks for images inside the body and make them inline.

    Before sending a message in HTML format, it is necessary to find
    all img tags contained in the body in order to rewrite them. For
    example, icons provided by CKeditor are stored on the server
    filesystem and not accessible from the outside. We must embark
    them as parts of the MIME message if we want recipients to
    display them correctly.

    :param body: the HTML body to parse
    """
    import os
    from email.mime.image import MIMEImage
    from urlparse import urlparse

    html = lxml.html.fromstring(body)
    parts = []
    for tag in html.iter("img"):
        src = tag.get("src")
        if src is None:
            continue
        o = urlparse(src)
        path = os.path.join(settings.MODOBOA_DIR, o.path[1:])
        if not os.path.exists(path):
            continue
        fname = os.path.basename(path)
        cid = "%s@modoboa" % os.path.splitext(fname)[0]
        tag.set("src", "cid:%s" % cid)
        with open(path, "rb") as fp:
            part = MIMEImage(fp.read())
        part["Content-ID"] = "<%s>" % cid
        part.replace_header(
            "Content-Type", '%s; name="%s"' % (part["Content-Type"], fname)
        )
        part["Content-Disposition"] = "inline"
        parts.append(part)
    return lxml.html.tostring(html), parts


class ComposeMailForm(forms.Form):

    """Compose mail form."""

    to = forms.CharField(
        label=_("To"), validators=[validate_email_list])
    cc = forms.CharField(
        label=_("Cc"), required=False, validators=[validate_email_list])
    cci = forms.CharField(
        label=_("Cci"), required=False, validators=[validate_email_list])

    subject = forms.CharField(
        label=_("Subject"),
        max_length=255,
        required=False
    )
    origmsgid = forms.CharField(label="", required=False)
    body = forms.CharField(required=False)

    def __init__(self, *args, **kwargs):
        """Custom constructor."""
        super(ComposeMailForm, self).__init__(*args, **kwargs)
        self.field_widths = {
            "cc": "11",
            "cci": "11",
            "subject": "11"
        }

    def _html_msg(self):
        """Create a multipart message.

        We attach two alternatives:
        * text/html
        * text/plain
        """
        msg = MIMEMultipart(_subtype="related")
        submsg = MIMEMultipart(_subtype="alternative")
        body = self.cleaned_data["body"]
        charset = "utf-8"
        if body:
            tbody = html2plaintext(body)
            body, images = make_body_images_inline(body)
        else:
            tbody = ""
            images = []
        submsg.attach(
            MIMEText(tbody.encode(charset), _subtype="plain", _charset=charset)
        )
        submsg.attach(
            MIMEText(body.encode(charset), _subtype="html", _charset=charset)
        )
        msg.attach(submsg)
        for img in images:
            msg.attach(img)
        return msg

    def _plain_msg(self):
        """Create a simple text message.
        """
        charset = "utf-8"
        text = MIMEText(self.cleaned_data["body"].encode(charset),
                        _subtype="plain", _charset=charset)
        return text

    def _build_msg(self, request):
        """Convert form's content to a MIME message.
        """
        editormode = parameters.get_user(request.user, "EDITOR")
        msg = getattr(self, "_%s_msg" % editormode)()

        if request.session["compose_mail"]["attachments"]:
            wrapper = MIMEMultipart(_subtype="mixed")
            wrapper.attach(msg)
            for attdef in request.session["compose_mail"]["attachments"]:
                wrapper.attach(create_mail_attachment(attdef))
            msg = wrapper
        return msg

    def to_msg(self, request):
        """Convert form's content to an object ready to send.

        We set headers at the end to be sure no one will override
        them.

        """
        msg = self._build_msg(request)
        set_email_headers(
            msg, self.cleaned_data["subject"], request.user.encoded_address,
            self.cleaned_data['to']
        )
        origmsgid = self.cleaned_data.get("origmsgid", None)
        if origmsgid:
            msg["References"] = msg["In-Reply-To"] = origmsgid
        return msg


class ForwardMailForm(ComposeMailForm):

    """Forward mail form."""

    def _build_msg(self, request):
        """Convert form's content to a MIME message.

        We also add original attachments (if any) to the new message.
        """
        from modoboa.extensions.webmail.lib import decode_payload

        mbox = request.GET.get("mbox", None)
        mailid = request.GET.get("mailid", None)
        msg = super(ForwardMailForm, self)._build_msg(request)
        origmsg = ImapEmail(request, False, "%s:%s" % (mbox, mailid))
        if origmsg.attachments:
            if not msg.is_multipart or not msg.get_content_subtype() == "mixed":
                wrapper = MIMEMultipart(_subtype="mixed")
                wrapper.attach(msg)
                msg = wrapper
            for attpart, fname in origmsg.attachments.items():
                attdef, payload = origmsg.fetch_attachment(attpart)
                attdef["fname"] = fname
                msg.attach(create_mail_attachment(
                    attdef, decode_payload(attdef["encoding"], payload)
                ))
        return msg


class FolderForm(forms.Form):
    oldname = forms.CharField(
        label="",
        widget=forms.HiddenInput(attrs={"class": "form-control"}),
        required=False
    )
    name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control"}))


class AttachmentForm(forms.Form):
    attachment = forms.FileField(label=_("Select a file"))

modoboa_webmail/templates/modoboa_webmail/attachments.html
{% extends "common/generic_modal_form.html" %}{% load url from future %}
{% load i18n %}
{% load static %}
{% block modalbody %}
{{ block.super }}

<div class="col-sm-12 text-center">
  <input type="button" class="btn btn-primary" id="submit" name="submit" value="{% trans 'Attach' %}" />
</div>

<div id="upload_status" style="display:none">
  <img src="{% static 'css/spinner.gif' %}" /> {% trans "Uploading.." %}
</div>
<iframe id="upload_target" name="upload_target" src="#" 
        style="width:0;height:0;border:0px solid #fff;"></iframe>
<div class="well" id="attachment_list">
  {% for att in attachments %}
  <div class="row">
    <div class="col-sm-12">
      <a href="{% url 'modoboa_webmail:attachment_delete' %}?name={{ att.tmpname }}"
         name="delattachment">
        <span class="fa fa-remove"></span>
      </a>
      <label>{{ att.fname }}</label>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

modoboa_webmail/templates/modoboa_webmail/compose.html
{% load i18n form_tags %}{% load url from future %}

<form class="form-horizontal" method="POST" action="{{ posturl }}" id="composemail">
  {% csrf_token %}

  <div id="compose-container">
    <div id="mailheader">
      <div class="form-group{% if form.errors.to %} has-error{% endif %}">
        <label class="col-sm-1 control-label" for="id_to">{% trans "To" %}</label>
        <div class="col-sm-8">
          <input id="id_to" name="to" class="form-control" value="{% if form.to.value %}{{ form.to.value }}{% endif %}"{% if form.to.errors %} placeholder="{% for error in form.to.errors %}{{ error }}{% endfor %}"  title="{% for error in form.to.errors %}{{ error }}{% endfor %}"{% endif %}>
        </div>
        {% if not form.cc.value %}
        <div class="col-sm-2">
          <button id="add_cc" class="btn btn-default btn-xs"><span class="fa fa-plus"></span> {% trans "Cc" %}</button>
          <button id="add_cci" class="btn btn-default btn-xs"><span class="fa fa-plus"> {% trans "Cci" %}</span></button>
        </div>
        {% endif %}
      </div>
      {% if form.cc.value %}
        {% render_field form.cc label_width="col-sm-1" %}
        {% render_field form.cci label_width="col-sm-1" %}
      {% else %}
        {% render_field form.cc label_width="col-sm-1" hidden=True %}
        {% render_field form.cci label_width="col-sm-1" hidden=True %}
      {% endif %}
      {% render_field form.subject label_width="col-sm-1" %}
      
    </div>
    
    <div id="body_container">
      {% if body %}
      <textarea id="id_body" name="body" class="form-control editor">{% if bodyheader %}{{ bodyheader }}{% endif %}
        {{ body }}
      </textarea>
      {% else %}
      <textarea id="id_body" name="body" class="form-control editor"></textarea>
      {% endif %}
    </div>
  </div>

</form>

modoboa_webmail/templates/modoboa_webmail/compose_menubar.html
{% extends "common/buttons_list.html" %}

{% load i18n %}

{% block extra_buttons %}
<div class="nav navbar-nav action-buttons btn-group">
  <a name="attachments" href="{% url 'modoboa_webmail:attachment_list' %}" class="btn btn-default">
    <span class="fa fa-paperclip"></span>
    {% trans "Attachments" %}
    <span id="attachment_counter">{% if attachment_counter %}({{ attachment_counter }}){% endif %}</span>
  </a>
</div>
{% endblock %}

modoboa_webmail/templates/modoboa_webmail/email_list.html
{% load i18n %}
{% load webmail_tags %}
{% load static %}

{% if with_top_div %}<div id="emails">{% endif %}
  {% for email in email_list %}
  <div id="{{ email.imapid }}" class="row email{% if email.style %} {{ email.style }}{% endif %}" data-page="{{ page }}">
    <div class="hidden-xs col-sm-1">
      <img name="drag" src="{% static 'pics/grippy.png' %}" class="draggable" />

      <input type="checkbox" />
    </div>
    <div class="col-xs-9 col-sm-9 openable">
      {{ email.subject|parse_imap_header:"subject" }}
      <p class="text-muted">
        {{ email.from|parse_imap_header:"from" }}
      </p>
    </div>
    <div class="col-xs-3 col-sm-2 text-right">
      {{ email.date|parse_imap_header:"date" }}
      <p>{% if email.answered %}<span class="fa fa-mail-reply"></span>{% endif %}{% if email.forwarded %} <span class="fa fa-mail-forward"></span>{% endif %}{% if email.attachments %} <span class="fa fa-paperclip"></span>{% endif %}</p>
    </div>
  </div>
  {% endfor %}
{% if with_top_div %}</div>{% endif %}

modoboa_webmail/templates/modoboa_webmail/folder.html
{% extends "common/generic_modal_form.html" %}
{% load i18n webmail_tags %}
{% block extrafields %}
<div id="folders2" class="well">
  <ul class="nav nav-pills nav-stacked">
    <li class="nav-header">{% trans "Parent mailbox" %}</li>
    {% print_mailboxes mboxes selected withunseen selectonly hdelimiter %}
  </ul>
</div>
{% endblock %}

modoboa_webmail/templates/modoboa_webmail/folders.html
{% load i18n webmail_tags %}
<ul class="nav nav-sidebar">
  {% print_mailboxes mboxes selected withunseen %}
</ul>

modoboa_webmail/templates/modoboa_webmail/headers.html
{% extends "common/mailheaders.html" %}{% load i18n %}{% load url from future %}
{% block extraheaders %}{% if attachments %}
  <div class="row">
    <div class="header">{% trans "Attachments" %}</div>
    <div class="value">{% url "modoboa_webmail:attachment_get" as url %}
      {% for key, fname in attachments.items %}
      <a href="{{ url }}?mbox={{ folder }}&mailid={{ mail_id }}&fname={{ fname }}&partnumber={{ key }}">{{ fname }}</a>
      {% endfor %}
    </div>
  </div>
{% endif %}{% endblock %}

modoboa_webmail/templates/modoboa_webmail/index.html
{% extends "twocols.html" %}{% load i18n lib_tags webmail_tags %}{% load url from future %}
{% load static %}
{% block pagetitle %}Webmail{% endblock %}
{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'jquery-ui/themes/base/all.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'modoboa_webmail/css/webmail.css' %}" />
{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{% static 'jquery-ui/jquery-ui.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/ckeditor/ckeditor.js' %}"></script>
<script type="text/javascript" src="{% static 'js/history.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.htmltable.js' %}"></script>
<script type="text/javascript" src="{% static 'js/searchbar.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.infinitescroll.js' %}"></script>
<script type="text/javascript" src="{% static 'modoboa_webmail/js/webmail.js' %}"></script>
<script type="text/javascript">
var webmail = undefined;

$(document).ready(function() {
    webmail = new Webmail({
        poller_interval: {{ refreshrate }},
        poller_url: "{% url 'modoboa_webmail:unseen_messages_check' %}",
        listing_url: "{% url 'modoboa_webmail:index' %}?action=listmailbox",
        move_url: "{% url 'modoboa_webmail:mail_move' %}",
        submboxes_url: "{% url 'modoboa_webmail:submailboxes_get' %}",
        delattachment_url: "{% url 'modoboa_webmail:attachment_delete' %}",
        deflocation: "{{ deflocation }}",
        defcallback: "{{ defcallback }}",
        ro_mboxes: {% tolist ro_mboxes %},
        trash: "{{ trash }}",
        hdelimiter: '{{ hdelimiter }}',
        mboxes_col_width: {{ mboxes_col_width }}
    });
});
</script>
{% endblock %}

{% block leftcol %}
<div class="leftcol-heading text-center">
  <a name="compose" class="btn btn-success btn-lg" href="compose">
    <span class="fa fa-edit"></span>
    {% trans "Compose" %}
  </a>
</div>

<div id="folders">
  {{ mboxes }}
</div>

<div id="left-toolbar" class="row">
  <div class="col-sm-2">
    <div id="mboxactions" class="btn-group dropup">
      <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
        <span class="fa fa-cog"></span>
      </button>
      {% mboxes_menu %}
    </div>
  </div>
  {% if quota != -1 %}
  <div id="quotabox" class="col-sm-10">
    <div id="quotabar" class="progress">
      <div class="progress-bar {% progress_color quota %}" role="progressbar" style="width: {{ quota }}%" aria-valuenow="{{ quota }}" aria-valuemin="0" aria-valuemax="100">{{ quota }}%</div>
    </div>
  </div>
  {% endif %}
</div>
{% endblock %}

{% block apparea %}
<div id="menubar" role="navbar"></div>
<div id="listing"></div>

{% endblock %}

modoboa_webmail/templates/modoboa_webmail/main_action_bar.html
{% extends "common/buttons_list.html" %}{% load i18n %}

{% block before_menubar %}
<div class="col-xs-5">
  {% include "common/email_searchbar.html" with extraopts=extraopts %}
</div>
{% endblock %}

{% block menubar_classes %}col-xs-7{% endblock %}

modoboa_webmail/templates/modoboa_webmail/upload_done.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head profile="http://www.w3.org/2005/10/profile">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <script type="text/javascript">
    {% if status == "ok" %}
    parent.webmail.upload_success("{{ fname }}", "{{ tmpname }}");
    {% else %}
    parent.webmail.upload_error("{{ error }}");
    {% endif %}
  </script>
</head>
<body></body>
</html>